// Generated by gencpp from file yx_turtles/AddTwoInts.msg
// DO NOT EDIT!


#ifndef YX_TURTLES_MESSAGE_ADDTWOINTS_H
#define YX_TURTLES_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <yx_turtles/AddTwoIntsRequest.h>
#include <yx_turtles/AddTwoIntsResponse.h>


namespace yx_turtles
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace yx_turtles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yx_turtles::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::yx_turtles::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::yx_turtles::AddTwoInts > {
  static const char* value()
  {
    return "yx_turtles/AddTwoInts";
  }

  static const char* value(const ::yx_turtles::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::yx_turtles::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::yx_turtles::AddTwoInts > 
template<>
struct MD5Sum< ::yx_turtles::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yx_turtles::AddTwoInts >::value();
  }
  static const char* value(const ::yx_turtles::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yx_turtles::AddTwoIntsRequest> should match 
// service_traits::DataType< ::yx_turtles::AddTwoInts > 
template<>
struct DataType< ::yx_turtles::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::yx_turtles::AddTwoInts >::value();
  }
  static const char* value(const ::yx_turtles::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yx_turtles::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::yx_turtles::AddTwoInts > 
template<>
struct MD5Sum< ::yx_turtles::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yx_turtles::AddTwoInts >::value();
  }
  static const char* value(const ::yx_turtles::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yx_turtles::AddTwoIntsResponse> should match 
// service_traits::DataType< ::yx_turtles::AddTwoInts > 
template<>
struct DataType< ::yx_turtles::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::yx_turtles::AddTwoInts >::value();
  }
  static const char* value(const ::yx_turtles::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YX_TURTLES_MESSAGE_ADDTWOINTS_H
